### ISSUE TITLE
Filter new app name for invalid chars

### ISSUE THREAD

**Issue by psych0d0g** [Heavybullets8/TT-Migration#14]
the feature introduced with: https://github.com/Heavybullets8/TT-Migration/issues/8
allows to rename the app to an arbitary string, not really validating for valid k8s names,
for example: it is possible to rename "app" to "app_new" (note the underscore) within the script, but you are not allowed to name a ressource in kubernetes containing an underscore.
afaik only valid chars are [a-zA-Z0-9] and "-", starting with an alphanumeric character.

It is not entirely clear from the script prompt and it is not validated as far as i can tell.

**Comment by Heavybullets8** [comment]
The script still validates that's the application exists. 
I can add input validation but the user should also know not to attempt to name their applications with invalid characters.

**Comment by psych0d0g** [comment]
yep, it would validate if it exists, but since you can not create an app with an underscore in its name, the validation would break, and its not entirely clear to the user how to proceed in this situation since the script tells the user to create "app_new" which is apperently not possible, a rerun without rename and added "-s" worked for me, but that was pure guesswork on my end :)

**Comment by Heavybullets8** [comment]
The documentation explains how to continue from a previous migration attempt.
https://github.com/Heavybullets8/TT-Migration#note

Either way, if it wasn't going to be you it'd be someone else. So I'll implement it tomorrow sometime. Thank you for the issue report.
