### ISSUE TITLE
Feature Request: Option to change app name during reinstallation

### ISSUE THREAD

**Issue by smokemyshoes** [Heavybullets8/TT-Migration#8]
Hi

It would be nice to be able to run the script with a flag that allow you to chose a new name for the app during re-installation.

I have very limited bash skills, but I imagine that it would be doable?

Best regards

**Comment by Heavybullets8** [comment]
Yeah. Just need to reprompt the app name and set the variable again. 
I'll see if I can do it this weekend.

**Comment by Heavybullets8** [comment]
Merged. 
Let me know if you come across any issues. Tested out fine on my end. 

To update:
Go to the directory of the script and run:
```
git pull
```
